### ISSUE TITLE
Global font size

### ISSUE THREAD

**Issue by kmlv** [kmlv/otree_express#57]
Hey Ankur,
Let's find the way to set a global css for all apps within this project. 
That is, a way to change the font size and some other styling in a single place/file?
Let me know what you find.

**Comment by ankur-gos** [comment]
Yeah we can factor out styles into its own stylesheet then link that stylesheet wherever needed.





On Sat, Nov 19, 2016 at 3:27 PM -0800, "kmlv" <notifications@github.com> wrote:












Hey Ankur,

Let's find the way to set a global css for all apps within this project.

That is, a way to change the font size and some other styling in a single place/file?

Let me know what you find.
