### ISSUE TITLE
emo_mauss_questionnaire crashes on production

### ISSUE THREAD

**Issue by ankur-gos** [kmlv/otree_express#64]
When running the emo_mauss_questionnaire is run on production during an experiment, field validation fails past the first page.

**Comment by ankur-gos** [comment]
#62 does not fix it

**Comment by gabrielapao** [comment]
I don't know why I can't run the server in this moment.  I saw the latest merge was from K.

**Comment by gabrielapao** [comment]
because only batson_questionnaire works well, I replicated some code of this on emo_mauss_questionnaire.
I'm going to commit these changes  just to my branch.

**Comment by ankur-gos** [comment]
@kmlv is this fixed can we close this?

**Comment by ankur-gos** [comment]
Fixed
